### PR TITLE
Code refactoring - Weather & Climate

### PR DESCRIPTION
**Pull request by edwardtfn**
- Code refactoring on Weather and Climate entities/pages in order to make easier to maintain and understand.
- Added support to custom units when provided by the weather entity. (#397)
- All the weather pages now shares the same code, increasing standardization
- Support for other forecast parameters when supported by the integration
- Removed empty rows between the forecast parameters

### CODE REVIEW

**Comment by el97** [comment]
Does this cover all weather providers? I'm using SMHI as a weather provider but the unit for wind is km/h when it should be m/s. I made sure that m/s is selected for wind but it still appears as km/h on my panel. https://www.home-assistant.io/integrations/smhi/

**Comment by edwardtfn** [comment]
I've tested several weather providers, including SMHI.
It will take the units from the parameters provided by the integration rather than a hard coded unit as it is now.

IMG_6127

**Comment by el97** [comment]
As you can see, I have the wind speed unit as m/s. I think this is my default since I put metric in the settings for home assistant here: https://my.home-assistant.io/redirect/general/  Skärmbild 2023-04-02 120738

**Comment by edwardtfn** [comment]
No problem. The new version will read that attribute, in your case "m/s" and in my case "km/h" and will use that when displaying in the panel.

**Pull request merged**
