### PR TITLE
Detailpage icons

### PR DESCRIPTION
**Pull request by bkbartk**
Hello,

this adds entity icons to the detail page when clicking them from button page.
I tried also to add this to the homepage buttons, but for somehow that failed, so maybe this will come later.

I now did the same thing 3 times, are functions of methods possible in blueprints? this seems a bit redundant to me.
Also, I was not sure where to put this in the release notes, so I didn't

### CODE REVIEW

**Comment by edwardtfn** [comment]
> I now did the same thing 3 times, are functions of methods possible in blueprints? this seems a bit redundant to me.
Also, I was not sure where to put this in the release notes, so I didn't

Unfortunately this is the way. In fact, a few months ago Home Assistant started supporting macros, but it is something that must be manually installed separated and cannot be embedded in a blueprint.

On ESPHome side this is a bit easier, but still requires additional files, what we avoided until this point.
 
However YAML supports anchors and aliases. We use it a bit in our code. There are many other areas where this could be applied, but as the code isn't following a pattern for naming, etc, you might have to rewrite some code to take advantage of anchors.

**Comment by edwardtfn** [comment]
Your code is based on `main`, so it's showing some conflict with latest code on `dev`, but please take a look on the changes I've proposed on the `open_entity_settings_page` calls based on anchors. As the page icon color is set on page open, we need now a code to keep it updated when color should change. 😉 
It saves a lot of coding and is not that hard to implement, but requires time.
There are lots of areas in the code with potential to use this. Even the anchor I've created could be used to button's icons, etc.
And then you have a single point for editing and the changes will be valid for all the areas using that anchor.

Please let me know your thoughts.

**Comment by bkbartk** [comment]
> Your code is based on `main`

oops, it should have been on dev.
my steps are
1. copy dev to local
2. change it locally
3. fork project
4. modify changes on git
5. copy back git to local to catch typo's or copy errors.
6. request pr.

but in step 4 I probably have selected the wrong branch(not for the 1st time, but last time I saw the word "main" in step 6).

For the other thing, I think I know what you mean and I think it really helps maintaining code. but I have to dive into code, and don't have the time for that right now.

So I will close this PR and hopefully I have time later this week to fix one and another in the new structure on the correct branch.

**Comment by edwardtfn** [comment]
The new release of ESPHome 2023.11.6 broke `dev` (and all other branches). I'm working on that now and come back to this later.

**Pull request closed without merging**
