### PR TITLE
make screen power available in HA 

### PR DESCRIPTION
**Pull request by bkbartk**
sorry,

I'm stubborn, but I sometimes prefer this over the 15 sec press because this can be done faster and I don't have to walk to the device.

### CODE REVIEW

**Comment by edwardtfn** [comment]
I don't think this should be in the `nspanel_esphome_core.yaml` as this is your specific request and not from all users and it shouldn't be used in a regular basis.

You can achieve this with a customization like this in your ESPHome yaml:

```yaml
switch:
  # Expose screen power to Home Assistant
  - id: !extend screen_power
    internal: false
```

The same would work if added to `nspanel_esphome_advanced.yaml`, where I think this makes more sense, but still I think this belongs more to [customizations](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization).

Please let me know your thoughts.

**Comment by bkbartk** [comment]
If it is just for me indeed it doesn't make sense to have this in the project.
But I actually think others might benefit from this as well however they might don't know it yet.
That's the reason I created this PR.
especially since I still see new TFT upload issues coming in I thought this would be helpful.
and I don't see any downsides to this change, no extra memory, no extra switch, only the switch which is there is visible.

(I actually didn't know it was possible to extend objects in esphome like this)

but if it's just for me please close the PR, if you think others can benefit you may accept.

or maybe upload this one should be added to `nspanel_esphome_addon_upload_tft.yaml` as it's only needed on tft upload
this last think it just a thought, you are in the lead of the project so I think those decisions are up to you to make.

**Comment by edwardtfn** [comment]
It's not only you, but it's not a lot of people and is mostly during the first time install. I agree that button could be useful, I'm just calling for a sanity check so we can think together the risks and benefits... And if possible, work on the problems that are requiring that kind of action.
We have to be careful not spamming users with lots of entities they don't have to use in normal conditions. Users will turn off that without knowing what is that doing... 😆 
Right now, when the system restarts the screen will turn on automatically, so this might reduce the risks.
When the screen starts, it will open the "boot" page and this triggers the boot sequence... maybe we should look at a way to skip the boot sequence in this case, so it would be much faster and this could even be used by some users who want to save energy by turning off the display during a trip, empty home, overnight, or so. It might be easy to implement (maybe I can look at this during this weekend).
And this is not my decision... It's an open source project and we welcome all the voices, so your opinion is important here. We might not be seeing something that may be clear to you, so we wanna take this kind of decision together.
For this we have this discussion area. 😉

**Comment by edwardtfn** [comment]
I've proposed some changes. Could you please help me with tests?

- Inform the Blueprint when the display is off, so it stops sending data.
- Bypass waits on the boot screen when boot was already completed.

**Comment by bkbartk** [comment]
So, one small change on my side, is a lot of work on yours ;)

I just installed the new file on one of my screens, and all seems to work.
"disabled_by_default " is a nice addition, needed to find how to add this in HA.
in the webinterface it's always added
image
but I think won't be an issue, as webserver is not added by default.

screen turning off and on works fine.

> Users will turn off that without knowing what is that doing

if they do that once they know;)

>  and this could even be used by some users who want to save energy by turning off the display during a trip

that conflicts with

>  when the system restarts the screen will turn on automatically

because when you have a power outage you loose the powersaving option afterwards.
I use sreen timeout for this. but turning off the full screen might prevent the babysitter from turning the heating to 26C (this only happened once)

all and all, I think those are good additions, and the boot sequence doesn't bother me personally, I actually don't know what this does, but I faster is always better, but I don't know if it would be an issue for anyone.

**Comment by edwardtfn** [comment]
> because when you have a power outage you loose the powersaving option afterwards.

True. But I will leave for whoever tries to use this switch to save power the responsibility to deal with those corner cases. 😉 
I think turn on the display when it boots is a must. Customization can be used to change that if someone wants.

> the boot sequence doesn't bother me personally, I actually don't know what this does, but I faster is always better, but I don't know if it would be an issue for anyone.

Basically the boot process waits for the API to connect and then triggers an event to Home Assistant informing the panel started. The blueprint uses this to send back all the settings for the panel (basically the home page settings, like colors, time format, etc), and the wake-up page info, which is used by the panel to show it.
This whole flow takes a while, and there are a couple of pauses so users would have a chance to read the info in the boot page (versions, IP address, baud rate, framework). None of those delays or getting info from HA are needed when the boot is already completed, but removing all of those would require a bit more work. I will look at this in the future, as I think it is good enough now.

**Pull request merged**
