### PR TITLE
Fan entities

### PR DESCRIPTION
**Pull request by tikismoke**
1st try to add fan.toggle (NO icon adds).

NEED a good review :)

### CODE REVIEW

**Comment by tikismoke** [comment]
Start working on #144 for the moment only toggle work from button, no details view with oscilate/speed/etc.

**Comment by Blackymas** [comment]
thanks we will check the code in the next days ;)

**Comment by tikismoke** [comment]
@Blackymas icon is correct i found my mistake

**Comment by deejaybeam** [comment]
Hi
Could you clean up the files from the pull-requests?
You just have changed the blueprint, but there are 7 changed files in the pull-request.

Additionaly, in the meanwhile there is also the option to confirm execution in section "##### Page Button - SHORT Press - Toggle Enities #####" - so you have to add the action to both options (with or without confirmation)

**Comment by tikismoke** [comment]
> Additionaly, in the meanwhile there is also the option to confirm execution in section "##### Page Button - SHORT Press - Toggle Enities #####" - so you have to add the action to both options (with or without confirmation)

For me it's done (the confirmation parts)

**Pull request merged**
