### PR TITLE
Update prebuilt

### PR DESCRIPTION
**Pull request by MichaelHeimann**
adds 
- md5 file requirement for ota_http
- psram
- blueprint compatibility with prebuilt AND non-prebuilt nspanels
- add climate_heat in default built
- configurable fw-url

removes
- verify "ssl_verify: false" - didn't work anyways and ssl is actually working just fine...

### CODE REVIEW

**Comment by edwardtfn** [comment]
I believe we can change the climate addon to be fully configurable via HA UI, including it's mode (heat/cool/dual). I will take a look at that later.

**Comment by edwardtfn** [comment]
As your code is behind `dev`, I believe it will be easier to just merge and then I make the proposed changes later.

**Comment by edwardtfn** [comment]
I've set the actions to compile the firmware automatically in any change on the ESPHome files. That will also create the MD5 files.
Just couldn't test those yet. :(

**Comment by MichaelHeimann** [comment]
Just did an update of my test-panel (wall_display) yaml - thanks for supporting that name in the blueprint. Worked. Nice!

**Comment by edwardtfn** [comment]
I will try to find some time to work on the climate in a way we could set everything from UI.

**Comment by MichaelHeimann** [comment]
Just found out the timezone on the panel is wrong as also discussed by @jesserockz in https://github.com/esphome/issues/issues/2868#issuecomment-1104511610_

Seems like ha syncs time but not timezone. That might need sntp as a workaround as long as ha doesn't get this fixed ...

**Comment by edwardtfn** [comment]
I've drafted a solution for this. It need some improvement to support Wi-Fi unavailable and to merge in another service.

**Comment by edwardtfn** [comment]
Hey @MichaelHeimann, I'm having some issues compiling the Wall Display firmware with ESP-IDF v5.1.5 (which will be the standard framework version for ESPHome).
We can always force the older version (v4.4.8, which is in use right now), but this will probably compromise the future of this pre-built firmware, so I wanna invest some time to trim it a bit and maybe even remove some functionality to make it viable, but before investing time on this I wanna know if you are really using it of if you are aware of anyone using it.
Please let me know and I will be happy to take the actions accordingly.

**Comment by MichaelHeimann** [comment]
Hi @edwardtfn , the firmware is in use one some devices.
I'd like to go with as little extra effort as possible though since I fear it'd lead to a death of prebuild sooner or later.
If there's something I can help with let me know.
Which parts are not compiling? Or which functionality is causing the troubles?

**Comment by MichaelHeimann** [comment]
Ah ... the wall displays are actually almost always thermostat replacements - so the climate heat is kind of a must.

Utilities pages? I don't exactly know what you mean with that but probably this could mean I don't use it. Is it the entities page?

**Comment by edwardtfn** [comment]
I've tried removing some pages, but that doesn't change that much the memory consumption. So I will pause those tests from now and not compile a Wall Display firmware for the next release, so we keep v4.3.12 there and skip v4.4.0, then I come back to this later and try to find some other way to find the memory we need...

**Comment by edwardtfn** [comment]
Sol I've tried a different approach which looks to be working. I've built the pre-built fir wares using idf v4.4.8. I will keep as this in the v4.4.0 and come back to this later.

**Comment by MichaelHeimann** [comment]
Cool, I thing the new IDF is not (yet) neccessary for any features so keeping the thermostat function and staying regulary build is nice to see :) Thanks for the effort, well appreciated!

**Pull request merged**
