### PR TITLE
Update nspanel_esphome.yaml

### PR DESCRIPTION
**Pull request by aceindy**
Add support for api encryption
(commented out)

### CODE REVIEW

**Comment by edwardtfn** [comment]
Could you please change your PR to have `dev` environment as your target?

**Comment by edwardtfn** [comment]
I believe this one is in line with #833 and just like that one, it's probably better to solve suggesting (instructions/manual) to use override in the upper level ESPHome setting of the device.

Please take a look at this comment: https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/833#issuecomment-1600334647

**Comment by Daddy1976** [comment]
pls add function fast_connect at wifi config

**Comment by edwardtfn** [comment]
> pls add function fast_connect at wifi config

You should create a feature request for this.

And you currently can add this in an easy way. Just add this to your ESPHome configuration file:

```yaml
##### My customisations - Start #####
wifi:
  fast_connect: true
##### My customisations - End #####
```

**Comment by edwardtfn** [comment]
This change is not needed anymore with https://github.com/Blackymas/NSPanel_HA_Blueprint/commit/028a8c4a6f459cdd6e037e313e96cbdf7289ac63

**Pull request closed without merging**
