### PR TITLE
Update nspanel_esphome_core.yaml

### PR DESCRIPTION
**Pull request by NetCom-Hymer**

### CODE REVIEW

**Comment by edwardtfn** [comment]
Hey @NetCom-Hymer, could you please explain why you wanna change this pin number?

**Comment by edwardtfn** [comment]
Pin 18 is used for psram.

**Comment by NetCom-Hymer** [comment]
Hi,

i have used only the Display oft he nspanel and i have connect a truma heater.

I use it to control the heater in the mobile home  remotely.
uart:
  - id: lin_uart_bus
    tx_pin: 22
    rx_pin: 23
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 2


Von: Edward Firmo ***@***.***>
Gesendet: Freitag, 7. Juni 2024 05:37
An: Blackymas/NSPanel_HA_Blueprint ***@***.***>
Cc: Stefan Neufuss ***@***.***>; Mention ***@***.***>
Betreff: Re: [Blackymas/NSPanel_HA_Blueprint] Update nspanel_esphome_core.yaml (PR #2139)


Hey @NetCom-Hymer<https://github.com/NetCom-Hymer>, could you please explain why you wanna change this pin number?

**Comment by edwardtfn** [comment]
Nice. But this should be as a customization on your system, not part of the main repo.

You probably can just add this to your panel's yaml as a customization to free-up that GPIO:

```yaml
switch:
  - id: !extend relay_1
    platform: template
    pin: !remove
    optimistic: true
    internal: true
```

This will make that relay virtual and free-up it's GPIO.0

**Comment by edwardtfn** [comment]
I will reject this, as it isn't to be part of the general implementation, but please feel free to continue the conversation as I will be happy to help.

**Comment by NetCom-Hymer** [comment]
Hi Edward,

many thx that you have supported me 😊

I have only one question where i stuck.

When i put the following into the Customization area i get the error:
Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'tf_uart', 'lin_uart_bus'.

# Customization area
##### My customization - Start #####
external_components:
  - source: github://Fabian-Schmidt/esphome-truma_inetbox
    components: ["truma_inetbox"]

uart:
  - id: lin_uart_bus
    tx_pin: 22
    rx_pin: 23
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 2

truma_inetbox:
  uart_id: lin_uart_bus

binary_sensor:
  - platform: truma_inetbox
    name: "CP Plus alive"
    type: CP_PLUS_CONNECTED

climate:
  - platform: truma_inetbox
    name: "Room"
    type: ROOM
#######################################################################################################################################
switch:
  - id: !extend relay_1
    platform: template
    pin: !remove
    optimistic: true
    #internal: true
##### My customization - End #####

Can you please assist what i have to do.

Best regards
Stefan

Von: Edward Firmo ***@***.***>
Gesendet: Freitag, 7. Juni 2024 07:25
An: Blackymas/NSPanel_HA_Blueprint ***@***.***>
Cc: Stefan Neufuss ***@***.***>; Mention ***@***.***>
Betreff: Re: [Blackymas/NSPanel_HA_Blueprint] Update nspanel_esphome_core.yaml (PR #2139)


Nice. But this should be as a customization on your system, not part of the main repo.

You probably can just add this to your panel's yaml as a customization to free-up that GPIO:

switch:

  - id: !extend relay_1

    platform: template

    pin: !remove

    optimistic: true

    internal: true

This will make that relay virtual and free-up it's GPIO.

**Comment by edwardtfn** [comment]
I've copy/paste your yaml to my panel, with no changes, and could successfully compile with ESPHome 2024.8.3.
Do you have anything else in your yaml which could be breaking this?

**Comment by NetCom-Hymer** [comment]
Hi Edward,
it comes when i add

- esphome/nspanel_esphome_advanced.yaml

Without i can compile.

So i am happy and i can continue – thx

Best greets to sweden
Stefan
Von: Stefan Neufuss
Gesendet: Dienstag, 3. September 2024 09:04
An: 'Blackymas/NSPanel_HA_Blueprint' ***@***.***>; Blackymas/NSPanel_HA_Blueprint ***@***.***>
Cc: Mention ***@***.***>
Betreff: AW: [Blackymas/NSPanel_HA_Blueprint] Update nspanel_esphome_core.yaml (PR #2139)

Hi Edward,

many thx that you have supported me 😊

I have only one question where i stuck.

When i put the following into the Customization area i get the error:
Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'tf_uart', 'lin_uart_bus'.

# Customization area
##### My customization - Start #####
external_components:
  - source: github://Fabian-Schmidt/esphome-truma_inetbox
    components: ["truma_inetbox"]

uart:
  - id: lin_uart_bus
    tx_pin: 22
    rx_pin: 23
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 2

truma_inetbox:
  uart_id: lin_uart_bus

binary_sensor:
  - platform: truma_inetbox
    name: "CP Plus alive"
    type: CP_PLUS_CONNECTED

climate:
  - platform: truma_inetbox
    name: "Room"
    type: ROOM
#######################################################################################################################################
switch:
  - id: !extend relay_1
    platform: template
    pin: !remove
    optimistic: true
    #internal: true
##### My customization - End #####

Can you please assist what i have to do.

Best regards
Stefan

Von: Edward Firmo ***@***.******@***.***>>
Gesendet: Freitag, 7. Juni 2024 07:25
An: Blackymas/NSPanel_HA_Blueprint ***@***.******@***.***>>
Cc: Stefan Neufuss ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Betreff: Re: [Blackymas/NSPanel_HA_Blueprint] Update nspanel_esphome_core.yaml (PR #2139)


Nice. But this should be as a customization on your system, not part of the main repo.

You probably can just add this to your panel's yaml as a customization to free-up that GPIO:

switch:

  - id: !extend relay_1

    platform: template

    pin: !remove

    optimistic: true

    internal: true

This will make that relay virtual and free-up it's GPIO.

**Comment by edwardtfn** [comment]
Ok, I can duplicate the issue with the advanced package and will come with a fix for the next release.

**Comment by edwardtfn** [comment]
Solved in `dev`.

**Pull request closed without merging**
