### PR TITLE
Alarm control panel

### PR DESCRIPTION
**Pull request by edwardtfn**
Implements an Alarm Control Panel page on NSPanel.

Solves https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/66
Solves https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/227
Solves https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/672
Partially solves https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/299#discussioncomment-4874612
Partially solves https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/64#issuecomment-1566204490
Partially solves https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/718

### CODE REVIEW

**Comment by fzambroni** [comment]
Is the alarm page available in dev?
I made all the installations available in DEV, and the icon appears available, but when I click, the page does not open.
I'm using Ring Alarm (no password) using Ring-Mqtt integration. I have the Alarm Panel available on my dashboard.
I am looking forward to testing this feature.

**Comment by edwardtfn** [comment]
Not yet. The first functioning version (no support for pin code) in a day or two.

**Comment by edwardtfn** [comment]
But if you update with the latest files at least the page should open.

**Comment by fzambroni** [comment]
> But if you update with the latest files at least the page should open.

Yes. It`s opening. Awesome. Thanks.

**Comment by pbranly** [comment]
Hi
I have a basic question: 
For switching to this last dev version, what is clear for me is that I need to download the last dev version for the tft and flash it, I need as well to download the last dev version of the blueprint and replace it in HA.
But for the esphome : isn’t it enough ton change main with dev in esphome configuration ?
Here is my code:
```
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  wifi_ssid: !secret SSID
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.1.8:8088/local/nspanel_us.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####


##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
#    ref: dev
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
Please clarify
Thanks
Phil

**Comment by edwardtfn** [comment]
That's right!

**Comment by fzambroni** [comment]
> I believe now we have a working code. Please let me know if you find issues.

I tested it and it didn't work. Buttons do not respond to commands (except disarm which is allowed to be selected).
The close button has a slight shadow at the top (just a detail).
Note: My alarm does not require a password (at the moment) to be armed/disarmed via the Home Assistant.

**Comment by edwardtfn** [comment]
> Note: My alarm does not require a password (at the moment) to be armed/disarmed via the Home Assistant.

I will take a look at that. I've tested only with alarms with a pin.

**Comment by edwardtfn** [comment]
Could you please go to your ESPHome configuration and double check if "Allow the device to make Home Assistant service calls" is enabled?

IMG_6390
IMG_6389

**Comment by fzambroni** [comment]
Yes, it's enabled.

Em qua., 16 de ago. de 2023 às 13:24, Edward Firmo ***@***.***>
escreveu:

**Comment by edwardtfn** [comment]
Could you add this to your ESPHome substitutions and try to capture ESPHome logs from when you press a button on the alarm page?

```yaml 
substitutions:
  verbose_log: "true"
```

**Comment by fzambroni** [comment]
I`ve changed the setting.

Only if I click on the "Disarm" the log change (14:07:43).

INFO ESPHome 2023.7.1
INFO Reading configuration /config/esphome/nsoffice.yaml...
INFO Detected timezone 'America/New_York'
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Starting log output from nsoffice.local using esphome API
INFO Successfully connected to nsoffice.local
[14:07:30][I][app:102]: ESPHome version 2023.7.1 compiled on Aug 16 2023, 13:52:10
[14:07:30][C][wifi:543]: WiFi:
[14:07:30][C][wifi:379]:   Local MAC: 94:3C:C6:C7:9F:48
[14:07:30][C][wifi:380]:   SSID: 'Zambroni'[redacted]
[14:07:30][C][wifi:381]:   IP Address: 192.168.5.11
[14:07:30][C][wifi:383]:   BSSID: 3C:5C:F1:9F:1D:54[redacted]
[14:07:30][C][wifi:384]:   Hostname: 'nsoffice'
[14:07:30][C][wifi:386]:   Signal strength: -63 dB ▂▄▆█
[14:07:30][C][wifi:390]:   Channel: 11
[14:07:30][C][wifi:391]:   Subnet: 255.255.252.0
[14:07:30][C][wifi:392]:   Gateway: 192.168.4.1
[14:07:30][C][wifi:393]:   DNS1: 192.168.4.1
[14:07:30][C][wifi:394]:   DNS2: 0.0.0.0
[14:07:30][C][logger:301]: Logger:
[14:07:30][C][logger:302]:   Level: DEBUG
[14:07:30][C][logger:303]:   Log Baud Rate: 0
[14:07:30][C][logger:305]:   Hardware UART: UART0
[14:07:30][C][uart.arduino_esp32:124]: UART Bus 0:
[14:07:30][C][uart.arduino_esp32:125]:   TX Pin: GPIO16
[14:07:30][C][uart.arduino_esp32:126]:   RX Pin: GPIO17
[14:07:30][C][uart.arduino_esp32:128]:   RX Buffer Size: 256
[14:07:30][C][uart.arduino_esp32:130]:   Baud Rate: 115200 baud
[14:07:30][C][uart.arduino_esp32:131]:   Data Bits: 8
[14:07:30][C][uart.arduino_esp32:132]:   Parity: NONE
[14:07:30][C][uart.arduino_esp32:133]:   Stop bits: 1
[14:07:30][C][ledc.output:160]: LEDC Output:
[14:07:30][C][ledc.output:161]:   Pin GPIO21
[14:07:30][C][ledc.output:162]:   LEDC Channel: 0
[14:07:30][C][ledc.output:163]:   PWM Frequency: 1000.0 Hz
[14:07:30][C][ledc.output:164]:   Bit depth: 16
[14:07:30][C][template.binary_sensor:028]: Template Binary Sensor 'nsoffice Nextion display'
[14:07:30][C][template.binary_sensor:028]:   Device Class: 'connectivity'
[14:07:30][C][uptime.sensor:031]: Uptime Sensor 'nsoffice uptime'
[14:07:30][C][uptime.sensor:031]:   Device Class: 'duration'
[14:07:30][C][uptime.sensor:031]:   State Class: 'total_increasing'
[14:07:30][C][uptime.sensor:031]:   Unit of Measurement: 's'
[14:07:30][C][uptime.sensor:031]:   Accuracy Decimals: 0
[14:07:30][C][uptime.sensor:031]:   Icon: 'mdi:timer-outline'
[14:07:30][C][template.text_sensor:020]: Template Sensor 'nsoffice current page'
[14:07:30][C][template.text_sensor:020]: Template Sensor 'nsoffice Notification Label'
[14:07:30][C][template.text_sensor:020]: Template Sensor 'nsoffice Notification Text'
[14:07:30][C][switch.gpio:068]: GPIO Switch 'nsoffice Screen Power'
[14:07:30][C][switch.gpio:091]:   Restore Mode: always ON
[14:07:30][C][switch.gpio:031]:   Pin: GPIO4
[14:07:30][C][template.number:050]: Template Number 'nsoffice Display Brightness'
[14:07:30][C][template.number:050]:   Unit of Measurement: '%'
[14:07:30][C][template.number:051]:   Optimistic: YES
[14:07:30][C][template.number:052]:   Update Interval: 60.0s
[14:07:30][C][template.number:050]: Template Number 'nsoffice Display Brightness Dimdown'
[14:07:30][C][template.number:050]:   Unit of Measurement: '%'
[14:07:30][C][template.number:051]:   Optimistic: YES
[14:07:30][C][template.number:052]:   Update Interval: 60.0s
[14:07:30][C][template.number:050]: Template Number 'nsoffice Temperature Correction'
[14:07:30][C][template.number:050]:   Unit of Measurement: '°C'
[14:07:30][C][template.number:051]:   Optimistic: YES
[14:07:30][C][template.number:052]:   Update Interval: 60.0s
[14:07:30][C][template.number:050]: Template Number 'nsoffice Page Timeout'
[14:07:30][C][template.number:051]:   Optimistic: YES
[14:07:30][C][template.number:052]:   Update Interval: 60.0s
[14:07:30][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'nsoffice Left Button'
[14:07:30][C][gpio.binary_sensor:016]:   Pin: GPIO14
[14:07:30][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'nsoffice Right Button'
[14:07:30][C][gpio.binary_sensor:016]:   Pin: GPIO27
[14:07:30][C][switch.gpio:068]: GPIO Switch 'nsoffice Relay 1'
[14:07:30][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[14:07:30][C][switch.gpio:031]:   Pin: GPIO22
[14:07:30][C][switch.gpio:068]: GPIO Switch 'nsoffice Relay 2'
[14:07:30][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[14:07:30][C][switch.gpio:031]:   Pin: GPIO19
[14:07:31][C][template.switch:068]: Template Switch 'nsoffice Notification unread'
[14:07:31][C][template.switch:091]:   Restore Mode: restore defaults to ON
[14:07:31][C][template.switch:057]:   Optimistic: YES
[14:07:31][C][template.switch:068]: Template Switch 'nsoffice Notification sound'
[14:07:31][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[14:07:31][C][template.switch:057]:   Optimistic: YES
[14:07:31][C][template.switch:068]: Template Switch 'nsoffice Confirmation Message'
[14:07:31][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[14:07:31][C][template.switch:057]:   Optimistic: YES
[14:07:31][C][template.switch:068]: Template Switch 'nsoffice Sleep mode'
[14:07:31][C][template.switch:079]:   Device Class: 'switch'
[14:07:31][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[14:07:31][C][template.switch:057]:   Optimistic: NO
[14:07:31][C][template.switch:068]: Template Switch 'nsoffice Relay 1 Local'
[14:07:31][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[14:07:31][C][template.switch:057]:   Optimistic: YES
[14:07:31][C][template.switch:068]: Template Switch 'nsoffice Relay 2 Local'
[14:07:31][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[14:07:31][C][template.switch:057]:   Optimistic: YES
[14:07:31][C][template.switch:068]: Template Switch 'nsoffice Relay 1 Local Fallback'
[14:07:31][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[14:07:31][C][template.switch:057]:   Optimistic: YES
[14:07:31][C][template.switch:068]: Template Switch 'nsoffice Relay 2 Local Fallback'
[14:07:31][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[14:07:31][C][template.switch:057]:   Optimistic: YES
[14:07:31][C][rtttl:018]: Rtttl
[14:07:31][C][restart.button:017]: Restart Button 'nsoffice Restart'
[14:07:31][C][adc:094]: ADC Sensor 'ntc_source'
[14:07:31][C][adc:094]:   Device Class: 'voltage'
[14:07:31][C][adc:094]:   State Class: 'measurement'
[14:07:31][C][adc:094]:   Unit of Measurement: 'V'
[14:07:31][C][adc:094]:   Accuracy Decimals: 2
[14:07:31][C][adc:104]:   Pin: GPIO38
[14:07:31][C][adc:119]:  Attenuation: 11db
[14:07:31][C][adc:133]:   Update Interval: 60.0s
[14:07:31][C][resistance:010]: Resistance Sensor 'resistance_sensor'
[14:07:31][C][resistance:010]:   State Class: 'measurement'
[14:07:31][C][resistance:010]:   Unit of Measurement: 'Ω'
[14:07:31][C][resistance:010]:   Accuracy Decimals: 1
[14:07:31][C][resistance:010]:   Icon: 'mdi:flash'
[14:07:31][C][resistance:011]:   Configuration: DOWNSTREAM
[14:07:31][C][resistance:012]:   Resistor: 11200.00Ω
[14:07:31][C][resistance:013]:   Reference Voltage: 3.3V
[14:07:31][C][version.text_sensor:021]: Version Text Sensor 'nsoffice ESPhome Version'
[14:07:31][C][version.text_sensor:021]:   Icon: 'mdi:new-box'
[14:07:31][C][nextion:117]: Nextion:
[14:07:31][C][nextion:118]:   Device Model:     NX4832F035_011C
[14:07:31][C][nextion:119]:   Firmware Version: 72
[14:07:31][C][nextion:120]:   Serial Number:    4165340198D6ED5C
[14:07:31][C][nextion:121]:   Flash Size:       16777216
[14:07:31][C][nextion:122]:   Wake On Touch:    True
[14:07:31][C][homeassistant.time:010]: Home Assistant Time:
[14:07:31][C][homeassistant.time:011]:   Timezone: 'EST5EDT,M3.2.0,M11.1.0'
[14:07:31][C][status:034]: Status Binary Sensor 'nsoffice Status'
[14:07:31][C][status:034]:   Device Class: 'connectivity'
[14:07:31][C][ntc:014]: NTC Sensor 'nsoffice Temperature'
[14:07:31][C][ntc:014]:   Device Class: 'temperature'
[14:07:31][C][ntc:014]:   State Class: 'measurement'
[14:07:31][C][ntc:014]:   Unit of Measurement: '°C'
[14:07:31][C][ntc:014]:   Accuracy Decimals: 1
[14:07:31][C][captive_portal:088]: Captive Portal:
[14:07:31][C][web_server:161]: Web Server:
[14:07:31][C][web_server:162]:   Address: nsoffice.local:80
[14:07:31][C][mdns:112]: mDNS:
[14:07:31][C][mdns:113]:   Hostname: nsoffice
[14:07:31][C][ota:093]: Over-The-Air Updates:
[14:07:32][C][ota:094]:   Address: nsoffice.local:3232
[14:07:32][C][ota:097]:   Using Password.
[14:07:32][C][api:138]: API Server:
[14:07:32][C][api:139]:   Address: nsoffice.local:6053
[14:07:32][C][api:141]:   Using noise encryption: YES
[14:07:32][C][wifi_info:009]: WifiInfo IPAddress 'nsoffice IP'
[14:07:32][C][wifi_info:011]: WifiInfo SSID 'nsoffice SSID'
[14:07:32][C][wifi_info:012]: WifiInfo BSSID 'nsoffice BSSID'
[14:07:32][C][wifi_signal.sensor:009]: WiFi Signal 'nsoffice RSSI'
[14:07:32][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[14:07:32][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[14:07:32][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[14:07:32][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[14:07:35][D][sensor:094]: 'ntc_source': Sending state 1.40200 V with 2 decimals of accuracy
[14:07:35][D][resistance:039]: 'resistance_sensor' - Resistance 8273.1Ω
[14:07:35][D][sensor:094]: 'resistance_sensor': Sending state 8273.12891 Ω with 1 decimals of accuracy
[14:07:35][D][ntc:026]: 'nsoffice Temperature' - Temperature: 29.3°C
[14:07:35][D][sensor:094]: 'nsoffice Temperature': Sending state 29.32819 °C with 1 decimals of accuracy
[14:07:37][D][sensor:094]: 'nsoffice RSSI': Sending state -64.00000 dBm with 0 decimals of accuracy
[14:07:39][D][text_sensor:064]: 'nsoffice NSPanel event': Sending state '{"page": "alarm", "component": "currentpage", "value": "pagechange", "entity": ""}'
[14:07:39][D][script.page_timer:1315]: start page-timer delay 20
[14:07:39][D][nspanelevent:929]: New page: alarm
[14:07:39][D][text_sensor:064]: 'nsoffice current page': Sending state 'alarm'
[14:07:39][D][nextion_textsensor:014]: Processed text_sensor "nspanelevent" state "{"page": "alarm", "component": "currentpage", "value": "pagechange", "entity": ""}"
[14:07:43][D][text_sensor:064]: 'nsoffice NSPanel local event': Sending state '{"domain": "alarm", "key": "disarm", "value": "click", "entity": "", "mui": "Disarm", "code_format": ""}'
[14:07:43][D][script:077]: Script 'page_timer' restarting (mode: restart)
[14:07:43][D][script.page_timer:1315]: start page-timer delay 20
[14:07:43][D][text_sensor.localevent:993]: domain=alarm
[14:07:43][D][text_sensor.localevent:994]: key=disarm
[14:07:43][D][text_sensor.localevent:995]: value=click
[14:07:43][D][text_sensor.localevent:996]: entity=
[14:07:43][D][text_sensor.localevent:997]: embedded=0
[14:07:43][D][service_call_alarm_control_panel:1537]: ESPHome remote service call
[14:07:43][D][service_call_alarm_control_panel:1538]: entity=
[14:07:43][D][service_call_alarm_control_panel:1539]: key=disarm
[14:07:43][D][service_call_alarm_control_panel:1540]: code_format=
[14:07:43][D][service_call_alarm_control_panel:1541]: pin=
[14:07:43][D][service_call_alarm_control_panel:1550]: service=alarm_control_panel.alarm_disarm
[14:07:43][D][service_call_alarm_control_panel:1553]: ESPHome remote service call
[14:07:43][D][nextion_textsensor:014]: Processed text_sensor "localevent" state "{"domain": "alarm", "key": "disarm", "value": "click", "entity": "", "mui": "Disarm", "code_format": ""}"
[14:07:43][W][component:204]: Component nextion.display took a long time for an operation (0.07 s).
[14:07:43][W][component:205]: Components should block for at most 20-30ms.

**Comment by fzambroni** [comment]
I recorded a video. You can see my setup in this link: https://youtu.be/n3a-ehd3Veo

**Comment by fzambroni** [comment]
When I create a pin to disarm, the screen works perfectly.  
WhatsApp Image 2023-08-16 at 2 46 39 PM
8eba2-d272-4083-a220-aa5fd5af12c3)

**Comment by edwardtfn** [comment]
I believe it's fixed.
You will have to update your blueprint and ESPHome.

The issue with the close icon I will take a look later.

**Comment by fzambroni** [comment]
I will be conducting a test today and let you know. So far, with PIN enabled works perfectly.

As a suggestion for future updates, including the ability to choose which buttons to display would be beneficial. In my situation, my alarm system only permits using the Home, Away, and Disarm buttons. The remaining buttons serve no purpose for me.

**Comment by edwardtfn** [comment]
Hiding the buttons is pretty easy, but arranging based on the number of buttons available is quite complex with a Nextion display, then we will have empty spaces on those buttons positions if they are hidden. I don't know what would be better in this case...
Maybe I can try to grey out a little bit more, like on the climate page.

**Comment by fzambroni** [comment]
Now it`s working without PIN. 
Thank you!

**Comment by primeroz** [comment]
@edwardtfn not sure if you want to keep getting feedback here on this closed issue but 

* I have an alarm panel configured using esphome `alarm_panel_component` https://esphome.io/components/alarm_control_panel/index.html 
* This creates an `alarm_control_panel` set of services and entities available in the home assistant dashboard that behaves the same as the manual one
image
image


It seems to be working well :+1:  

Just wanted to highlight a couple of things , not sure if they are already on the roadmap or not 

* the `Alarm States` like `Night` , `Away` , `Disarmed` and so on are properly represented and the buttons do turn green accordingly
* when the alarm panel is in a `transient` state like `ARMING` , `PENDING` or `TRIGGERED` there is no visual feedback of any sort : All the Buttons are gray ( see below picture )

PXL_20230817_094241510


would it make sense to have something like ( just throwing a bunch of ideas out there ) 
* turn button ( or all buttons if is not easy to understand which button should be turned on ) to `orange` when "PENDING"
* turn button ( or all buttons ) to `red`  when `TRIGGERED` ?
* turn button ( or all buttons ) to `yello` when `ARMING` ? 
* use the notification service when alarm is triggered ? 
* change color of the `shield` icon on the homepage ?

**Comment by edwardtfn** [comment]
Thanks a lot for your feedback.

About feedback on button press, I would expect the button becoming amber until the new state is updated. Isn't that happening?

I like the idea of having the icon on Home page changing color. I will take a look at that.

About the colors for triggered and arming, I'm stuck on finding which actions the user should do in the panel on that case. Could you please clarify? What should you do in your panel if the alarm triggers?
That will help me difining the behaviour of buttons.

**Comment by primeroz** [comment]
> About feedback on button press, I would expect the button becoming amber until the new state is updated. Isn't that happening?

No, not for me at least ( remember i use a [very brand new esphome component](https://esphome.io/components/alarm_control_panel/index.html) with a very recent home assistant integration ... so it could be slightly different form the `manual alarm panel` ) 

In my case it all goes gray while `ARMING` then it will turn on `green` on the button pressed

I will try to have a look at the code this afternoon see if i can see why it is failing in my case, if you could point me to the code that is supposed to handle the `amber` code that would be great.  starting tomorrow i am off for a week so i don't have too much time i can spend on it right now :pray: 

> I like the idea of having the icon on Home page changing color. I will take a look at that.

:+1: 

> About the colors for triggered and arming, I'm stuck on finding which actions the user should do in the panel on that case. Could you please clarify? What should you do in your panel if the alarm triggers?

In my opinion is more a `visual feedback` than anything else. for example , excluding a real intrusion from a real thief, when overnight someone might trigger the alarm by moving into an alarmed zone, when going to the `panel` i would expect something to be `red` to show me that the alarm was triggered. 

Same for `pending` when entering my home i need some `feedback` to remember i have to disable the alarm ... ideally it would be sound but at least something on the panel next to the door will do.  

maybe is just me, but i am all about `visual` and `sound` feedbacks ... i am already planning to try and get the `nspanel` buzzers to play something when `ARMING` or `PENDING` so that people will know what's going on.

**Comment by edwardtfn** [comment]
I would ask you guys to move this discussion to #984 as this thread we are using is related to a cancelled PR.

**Pull request closed without merging**
