### PR TITLE
Use Home Assistant icon selector for icons

### PR DESCRIPTION
**Pull request by edwardtfn**
Replace all icon selection to Home Assistant native icon selector, improving the user experience.

Note: As not all the MDI icons are available for Nextion, if one of those icons is selected it will be displayed as a question mark `?`.

This will enable icons in the Entities pages in the future, as now it's possible to use the attribute `icon` when available and convert it in the same way to a Nextion icon.

This should not be a breaking change as previously selected icons should also be supported.

### CODE REVIEW

**Comment by denes44** [comment]
This method does not support all the icons that was available before.
For example I used mdi:lightbulb-auto (F7FF) before, but now it is not in the list.

**Comment by edwardtfn** [comment]
Mmmm
It should be there. I would expect all the same icons from before.
I will take a look.

**Comment by edwardtfn** [comment]
@denes44, could you please try it again? I've fixed with #752 which was just merged into `dev`.

**Comment by denes44** [comment]
It is good now, thanks.

**Pull request merged**
