### PR TITLE
climate fix

### PR DESCRIPTION
**Pull request by bkbartk**
My climate also has a current temperature while off.

I think most have.

Next to that I wanted to add set temperature "temperature" but couldn't find how to add a new line.
and for heat I wanted a red background, and for cool a blue, however text background color only applied to texts.

anyway, now it's only a small fix.

### CODE REVIEW

**Comment by edwardtfn** [comment]
> for heat I wanted a red background, and for cool a blue, however text background color only applied to texts. 

We have stardardized icons type and color for climate in many other places... Shouldn't that be better to show than text background in this case?

**Comment by edwardtfn** [comment]
About this PR, will you be able to test after merging? I'm travelling today and tomorrow and don't have a panel with me. 😩

**Comment by bkbartk** [comment]
> > for heat I wanted a red background, and for cool a blue, however text background color only applied to texts.
> 
> We have stardardized icons type and color for climate in many other places... Shouldn't that be better to show than text background in this case?

That indeed would be better, text background was ugly so I changed it back

**Comment by bkbartk** [comment]
> About this PR, will you be able to test after merging? I'm travelling today and tomorrow and don't have a panel with me. 😩

I would,
but I'm not really sure this if this is the correct file
I installed this one now as blueprint
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/f9ff2edcd645a8f189e187036cd86b9b9d17a485/nspanel_blueprint.yaml

**Comment by edwardtfn** [comment]
This one: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/dev/nspanel_blueprint.yaml

But if you tested from your branch it should be exactly the same right now.

**Pull request merged**
