### PR TITLE
Text Reverese for Hebrew translation

### PR DESCRIPTION
**Pull request by leranp**
The Nextion show the Hebrew chracters reverese , so i had to reverese it again

### CODE REVIEW

**Comment by edwardtfn** [comment]
What about other text coming from sensors? Are those shown properly in the panel?

My question is due to if we have to invert not only the hard coded strings it would worth working in some library to reverse all the strings before displaying.

**Comment by leranp** [comment]
> What about other text coming from sensors? Are those shown properly in the panel?
> 
> My question is due to if we have to invert not only the hard coded strings it would worth working in some library to reverse all the strings before displaying.

Unfortunately the text coming from HA also needs to be invert , maybe a script in the Esphome that reverse the character will do the job

**Comment by edwardtfn** [comment]
I will look at that... there are multiple functions calling the display of text, but let me see...

How this works for numbers? And units of measurement?

**Comment by edwardtfn** [comment]
I will merge this PR for now but we can still working on the reversing engine and chatting here.

**Comment by leranp** [comment]
> I will look at that... there are multiple functions calling the display of text, but let me see...
> 
> How this works for numbers? And units of measurement?

Thank you,
The numbers and unit are fine.
There's also a problem with the Hebrew characters in the page buttons , there's no space for them, and they appear in wrong way, this is an example, the button with string "מסדרון" but the "מ" disappear and a character "ס" appear in a new line

**Comment by edwardtfn** [comment]
I will take a look at that.
Do you mind reporting this thing with button pages as a bug?

**Pull request merged**
