### PR TITLE
reformat code - remove obsolete spaces

### PR DESCRIPTION
**Pull request by bakito**
Some yaml files contain lots of obsolete spaces.
I the IDE does automatic cleanup on save, many files are changed without actually having any changes.

This PR does a cleanup on these yaml files. Only obsolete spaces at line endings are removed.

### CODE REVIEW

**Comment by Blackymas** [comment]
is there a function for this in vscode?

I can not take over because a huge part of the code has changed

**Comment by bakito** [comment]
I'm not so familiar with vscode, but have a look at https://stackoverflow.com/questions/30884131/remove-trailing-spaces-automatically-or-with-a-shortcut

**Comment by chpego** [comment]
Use Prettier !

**Comment by Blackymas** [comment]
done thanks

**Pull request closed without merging**
