### PR TITLE
Update T.Chinese translation and Zi fonts.

### PR DESCRIPTION
**Pull request by bluefoxlee**

### CODE REVIEW

**Comment by edwardtfn** [comment]
#1359

**Comment by edwardtfn** [comment]
With those fonts the boot page is looking quite broken. I will have to add some space for strings later.

**Comment by bluefoxlee** [comment]
What if you re-generate Ubuntu typeface with CJK character set? 
Not sure if I am using correct Ubuntu typeface, but I will test it later too.

**Comment by edwardtfn** [comment]
Well, I can try, but it was @Blackymas who generated the previous one, so I don't know if I will do any different than you.
It would be nice if you chare your latest set of chars anyways, so we keep with the font files for when someone else tries to generate these fonts in the future.

Anyway, the problem if probably with the font size. As you used a different font size, it is breaking with the latin chars. If the problem is only with latin, then probably is better if I just change spacing on the boot page (which is the only one we cannot translate at least until the Blueprint gets connected).
If the font size will be an issue with other pages also, then we should probably try to keep the font sizes the same as used for the original version, which woukd be the safe way.

Could you please take a look on how it looks on the other pages and let me know?

**Comment by bluefoxlee** [comment]
> Could you please take a look on how it looks on the other pages and let me know?

Will do. 
Will it be better (for me) to make a mixed font without increase any size in order to avoid those space issues? go for safe way .

**Comment by bluefoxlee** [comment]
It's difficult then I thought. Have been tested on dozens different fonts. Need to match with size, English font. Can't missing for S.Chinese/Korean/Japanese. I finally find one and start to test on it from yesterday. But I do notice few issues. Should I just post/report it with screenshot here?

BTW, is there any way to capture a nice and clean shot of the screen? wonder how you capture the screenshot. 

And......Happy New Year!

**Comment by edwardtfn** [comment]
> wonder how you capture the screenshot

I've started drafting a manual on this, but basically I use the DEBUG option from Nextion Editor and type all the data I wanna there, but I'm adding those commands to a file: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/dev/dev/manuals_screenshots.md

Another way is to use that same screen (debug) and connect to a esp32, but that is a bit hard to establish connection.

**Comment by bluefoxlee** [comment]
Flashed two other nspanel, now I got eu/us/us land for testing and report. Updated fonts (adjust size & include HKSCS for Hong Kong). Will report issues below.

**Comment by bluefoxlee** [comment]
Nspanel US

1. Characters background become black on button page. Fine for eu/us_land
IMG_0553

2. Entities Pages shows unknown icon if icon option is empty
IMG_0551

3. More like feature request for Chinese/Japanese. Both languages needs to add "日" (day) after days. I add another option "value: '%b%-d日%A'" to skip this issue temporary.
IMG_0550

**Comment by bluefoxlee** [comment]
Reserve for EU

**Comment by bluefoxlee** [comment]
Reserve for US_land

**Pull request merged**
