### PR TITLE
Add Fan speed settings page

### PR DESCRIPTION
**Pull request by edwardtfn**
Add an initial fan speed control page for fans supporting speed control. Add speed (%) info in the buttons pages.

Solves #404 
Solves #791 
Solves https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/718#discussioncomment-5786106

### CODE REVIEW

**Comment by snoopsbne** [comment]
Thanks for this - I am noticing an issue though. Possibly because my fans are 3-speed. So 0%-33%-66%-100%. The tile/button displays the speed correctly but when using the slider, the speed is changed correctly but the slider reverts back to the old speed and does not reflect the current speed. Closing the dialog and reopening it displays the correct/current speed on the slider.

**Comment by edwardtfn** [comment]
I will test this case (3 speeds) tomorrow and come back to you.

**Comment by snoopsbne** [comment]
Yeah, it seems it does not wait long enough for the component to respond and just reverts back to the old speed. FYI this is using ifan02/03 controllers, one via a Tasmota another using the HACS Sonoff Lan integration.

**Comment by edwardtfn** [comment]
So, I've just changed the update engine, but I cannot test right now. If you have a change, please give it a try and come with your feedback.
I will run more tests tomorrow, but I'm pretty confident, as this is now following the same pattern as other settings pages.

**Pull request merged**
