### PR TITLE
Simplifying code - Input area

### PR DESCRIPTION
**Pull request by edwardtfn**
Used YAML alias to simplify the code in the `input:` area. This will make easier to maintain as it creates single points of changes, promoting consistence.

### CODE REVIEW

**Comment by albinmedoc** [comment]
This is really good and should absolutely be implemented to reduce inconsistence when adding new features. 

As you said, makes it easier to maintain as changes are only made at a single point.

**Comment by albinmedoc** [comment]
It also shrinkens the blueprint and makes it more readable.

**Comment by albinmedoc** [comment]
This PR shrunk the blueprint by 9.02%.

**Comment by edwardtfn** [comment]
> This PR shrunk the blueprint by 6.5%.

That's true if you count number of lines of code only, but this is not affecting the memory consumption in the panel or the amount of processing in HA, so my point here this is more about making it easier to maintain.

**Comment by deejaybeam** [comment]
Very cool solution - like it, and I think we could use aliases on many other parts in the code too

**Comment by edwardtfn** [comment]
Definitely there are many areas where alias could be applied... I just want to start this...

**Pull request merged**
