### PR TITLE
Multiline support for buttons on buttonpages

### PR DESCRIPTION
**Pull request by denes44**
I did the changes I proposed in #738.

- Changed the button's label textbox height +20 pixel
- Changed the button's label textbox Y position -20 pixel
- Changed the button's label textbox maximum text length to 22 (2x10 plus the \r)
- Changed the blueprint to replace the \r to a space in the lightsetting and climate page (we don't need two rows here, also found a possible bug for the coversettings page: #739)

As you can see in this picture, one line displays as before, but now there is possible to use two lines:
nspanel_multiline
Unfortunately the center aligning not working the best way on the Nextion display.

### CODE REVIEW

**Comment by denes44** [comment]
Meanwhile #739 was fixed in #741, so I updated this PR so that the line brake gets removed for the cover setting page as well.

**Comment by edwardtfn** [comment]
@denes44, have you tested this in both EU and US panel? Please let me know and I can test a bit with the model you haven't tested.

**Comment by edwardtfn** [comment]
By the way, do you think this will solve #664?

**Comment by edwardtfn** [comment]
This solves #738 

* I've added this just to link this PR to the discussion

**Comment by denes44** [comment]
> @denes44, have you tested this in both EU and US panel? Please let me know and I can test a bit with the model you haven't tested.
I only tested on EU panel.
I'm not sure if I can upload the US TFT file to an EU display. Does it cause any problem other than the display will be hard to look at? :)

**Comment by denes44** [comment]
> By the way, do you think this will solve #664?

Probably not. The display behaves very strange.
For example, when I did this, in the Nextion editor I could enter 20 characters with a newline to a text field which length is 20.
But if I sent the string from HA with `\r` the display only showed 18 characters...

**Comment by edwardtfn** [comment]
> I only tested on EU panel.

No problem, I can test in a US panel later. I will let you know the results.

> I'm not sure if I can upload the US TFT file to an EU display. Does it cause any problem other than the display will be hard to look at? :)

It shouldn't cause any damage, but it will be sideways and therefore a bit hard to play with. :D

> Probably not. The display behaves very strange.
For example, when I did this, in the Nextion editor I could enter 20 characters with a newline to a text field which length is 20.
But if I sent the string from HA with \r the display only showed 18 characters...

Ok, so looks like it counts the chars on `\r`, so why don't you set the limit to 22? If the `\r` is not there and users add more than 10 chars it will look broken anyways, so changing the limit to 22 shouldn't be an issue other than additional memory reserved for those, right?

By the way, will `\n` gives the same results? If you don't know, don't worry. I can try myself later.

**Comment by denes44** [comment]
Yes I did that after I realized that, edited the lengths to 22.
`\n` did not worked for me, only `\r`

**Comment by edwardtfn** [comment]
I've tried with US model and looks to be working fine.
IMG_3361

> \n did not worked for me, only \r

Same with me. When I tried `\n` nothing was shown.

**Comment by edwardtfn** [comment]
Unfortunately no, this was never merged.

**Comment by edwardtfn** [comment]
This PR was removed by the author before the merging, so it's totally out of our radar.
I don't see any problem about working on this in the near future, it's probably quite straight, but as this will require changing field sizes (and memory consumption) on the TFT files, I'd like to hear from @Blackymas before any investment of time.

**Pull request closed without merging**
