### PR TITLE
Added binary_sensor to supported button entities

### PR DESCRIPTION
**Pull request by naofireblade**
Hi, I added binary_sensor to the supported entities. Can you provide a resource file (.psd or something else) so i can create icons for different device classes of binary_sensor?

### CODE REVIEW

**Comment by Blackymas** [comment]
Hi looks great we adopt so - thank you!

**Comment by naofireblade** [comment]
I used the icon from automation, I really like to provide icons for the most common device classes (https://www.home-assistant.io/integrations/binary_sensor/) and a generic sensor icon for others. How did you generate the existing icons so I can provide more?

**Comment by naofireblade** [comment]
@Blackymas do you have any icon resources for me to work with?

**Comment by Blackymas** [comment]
i will check I work with adobe express - I will come back to you

**Pull request merged**
