### PR TITLE
Update nspanel_blueprint.yaml

### PR DESCRIPTION
**Pull request by MichaelHeimann**
fixes "Error: TypeError: '>' not supported between instances of 'list' and 'int'"

### CODE REVIEW

**Comment by edwardtfn** [comment]
Mmmmm
Timezone shouldn't be a list there. 🤔

**Comment by edwardtfn** [comment]
Which timezone are you trying?

**Comment by edwardtfn** [comment]
Trying the old code, it fails even when no coma.

**Comment by edwardtfn** [comment]
I don't have access to my panels now, but at least that crash was fixed now.

**Comment by MichaelHeimann** [comment]
Very nice - works now!  Thanks!

**Comment by edwardtfn** [comment]
We have to add this new timezone selector to the release notes...

**Pull request merged**
