### PR TITLE
Human readable Uptime

### PR DESCRIPTION
**Pull request by WZYProjects**
Make the Uptime sensor human readable in ESPHome webserver and Home Assistant

### CODE REVIEW

**Comment by edwardtfn** [comment]
Have you tried [this one](https://community.home-assistant.io/t/uptime-sensor-in-hours-or-days/116392/33?u=edwardtfn)? It looks cleaner but, most important should deal with localization as your code will be always in English (and some other languages sharing the same initials).

**Comment by WZYProjects** [comment]
That looks good in Home Assistant but gives a weird number in ESPhome web server.
I would prefer the [1st commit](https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/986/commits/d3dffff634503c1955644628727ca2831c6431d6) since the uptime is a diagnostic sensor and I think it's better to be displayed correctly in both frontends.

**Comment by edwardtfn** [comment]
I see your point...
It looks nice in Home Assistant:
IMG_6391

But shows only the raw number (Unix format timestamp?) on the Web, which is almost useless for troubleshooting:
IMG_6393

**Comment by edwardtfn** [comment]
> I would prefer the [1st commit](https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/986/commits/d3dffff634503c1955644628727ca2831c6431d6) since the uptime is a diagnostic sensor and I think it's better to be displayed correctly in both frontends.

if you don't like, you don't have to go the direction I'm pointing... I was just opening the discussion.😉
I liked the 2nd more, but that is probably because I never use the Web interface.
I'm fine with both ways.

Let's see if @Blackymas and @deejaybeam have anything to say here.

**Comment by edwardtfn** [comment]
I'm really happy for you contributing to this. 🙂

**Comment by WZYProjects** [comment]
I tried a few different ways and what I found during testing is that the dev branch is reseting the uptime when I restart Home Assistant. That doesn't happen in the main branch.

**Comment by edwardtfn** [comment]
Probably that call to `update_timestamp` should be in the boot process (righh after the api connection on the display startup). As it is now it will run every time the time component is refreshed, which definitely will happens when the api is reconnected.
As it is now is measuring more the API connection time (which is also a nice info for troubleshooting) than uptime.

**Comment by edwardtfn** [comment]
I would also propose to rename the sensor, as keeping the same name is generating an error on Home Assistant (related to the previous sensor having Unit of Measuring is "s" which is not compatible with timestamp).

image

I will make a new commit for this. Please let me know your thoughts.

**Comment by edwardtfn** [comment]
I'm merging this to avoid more complex merges with other things later, but let's keep the discussion here.
We can always revert back or change to something else, but ideally we should get to a conclusion before the release to avoid changing things all the time. ;)

**Comment by WZYProjects** [comment]
That's perfect, I will keep on reading and learning and maybe in the future we could have 2 sensors, device and api uptime.

**Comment by WZYProjects** [comment]
it's giving me random timestamps everytime I restart Home Assistant but moving the - sensor.template.publish: to the bottom fixes the problem.

**Comment by edwardtfn** [comment]
I saw your message about moving the publish to the bottom, but now I cannot see it anymore? Are you gonna submit a new PR here?

**Comment by WZYProjects** [comment]
The sensor was publishing random timestamps but after a cold start it started to report correctly. Now after a few days it's publishing random timestamps again everytime I restart the panel. I'm going to do more testes with another panel.

**Comment by edwardtfn** [comment]
Why don't you create a new PR for that? 😉

**Comment by edwardtfn** [comment]
#998

**Pull request merged**
